Updated alert dialog tokens
adobe/spectrum-tokens-studio-data pull request #91
Opened 2024-04-05 15:04 UTC by KayiuCarlson

## Description

Updated alert dialog tokens by creating new and deprecated old Title and Description font size tokens.

## Motivation and context

Added the word "font" in the font size token naming for alert dialog.

## Related issue

n/a

## Types of changes

n/a

<li> [ ] Patch (bug fixes, typos, mistakes; non-breaking change which fixes an issue) </li>
<li> [x] Minor (add a new token, changing a value; non-breaking change which adds functionality) </li>
<li> [x] Major (deleting a token, changing token value type; fix or feature that would cause existing functionality to change) </li>

## Checklist:

<li> [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html). </li>
<li> [x] I updated the token in all applicable sets. This applies if updating, adding, or deleting a token that has data across different sets (for example, if the value differs across color themes.) </li>

2024-04-05 18:47 UTC, mrcjhicks commented
**[TESTING spectrum2-non-colors](https://github.com/adobe/spectrum-tokens-studio-data/actions/runs/8574369533)**

READING spectrum-tokens: `/spectrum-tokens/packages/tokens/src/`
READING   tokens studio: `/spectrum-tokens-studio-data/src/tokens-studio/spectrum2-non-colors/`
TOKENS STUDIO DATA IS NON-COLOR ONLY

<details><summary>STUDIO SYNC SUMMARY</summary><p>

```
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 alert-dialog-description-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component.🚫 alert-dialog-title-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.alert-dialog-description-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.alert-dialog-description-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/desktop.alert-dialog-title-font-size
UPDATED METADATA - SPECTRUM UUID: spectrum2/layout.component/mobile.alert-dialog-title-font-size
```
</p></details>

<details><summary>SPECTRUM SYNC SUMMARY</summary><p>

```
NEW TOKENS: (21) in-field-button-edge-to-fill-small/desktop, in-field-button-edge-to-fill-extra-large/desktop, in-field-progress-circle-edge-to-fill/desktop, in-field-progress-circle-size-75/desktop, in-field-progress-circle-size-100/desktop, in-field-progress-circle-size-200/desktop, in-field-progress-circle-size-300/desktop, in-field-button-edge-to-fill-small/mobile, in-field-button-edge-to-fill-extra-large/mobile, in-field-progress-circle-edge-to-fill/mobile, in-field-progress-circle-size-75/mobile, in-field-progress-circle-size-100/mobile, in-field-progress-circle-size-200/mobile, in-field-progress-circle-size-300/mobile, combo-box-visual-to-field-button, in-field-button-edge-to-fill-medium, in-field-button-edge-to-fill-large, alert-dialog-description-font-size/desktop, alert-dialog-description-font-size/mobile, alert-dialog-title-font-size/desktop, alert-dialog-title-font-size/mobile
MODIFIED TOKENS: (6) alert-dialog-description-size, alert-dialog-title-size, combo-box-visual-to-field-button-extra-large, combo-box-visual-to-field-button-large, combo-box-visual-to-field-button-medium, combo-box-visual-to-field-button-small
DEPRECATED TOKENS: (17) combo-box-quiet-minimum-width-multiplier, combo-box-visual-to-field-button-small/desktop, combo-box-visual-to-field-button-small/mobile, combo-box-visual-to-field-button-medium/desktop, combo-box-visual-to-field-button-medium/mobile, combo-box-visual-to-field-button-large/desktop, combo-box-visual-to-field-button-large/mobile, combo-box-visual-to-field-button-extra-large/desktop, combo-box-visual-to-field-button-extra-large/mobile, combo-box-visual-to-field-button-quiet, alert-dialog-title-size/desktop, alert-dialog-title-size/mobile, alert-dialog-description-size/desktop, alert-dialog-description-size/mobile, in-field-button-edge-to-fill, drop-shadow-y, drop-shadow-blur
CHANGED VALUES: (7) combo-box-visual-to-field-button-extra-large/desktop, combo-box-visual-to-field-button-large/desktop, combo-box-visual-to-field-button-medium/desktop, combo-box-visual-to-field-button-quiet, combo-box-visual-to-field-button-small/desktop, alert-dialog-description-size/desktop, alert-dialog-title-size/desktop
CHANGED SCHEMAS: (5) combo-box-visual-to-field-button-extra-large, combo-box-visual-to-field-button-large, combo-box-visual-to-field-button-medium, combo-box-visual-to-field-button-quiet, combo-box-visual-to-field-button-small
```
</p></details>

TEST COMPLETE

2024-04-05 21:13 UTC, lynnhao approved these changes
Looks good, thank you!

2024-04-10 11:42 UTC, karstens requested changes
please see my comment in slack: https://adobedesign.slack.com/archives/GTZ7NSNR0/p1712749311910149?thread_ts=1712329548.189499&cid=GTZ7NSNR0

2024-04-11 10:43 UTC, karstens approved these changes

2024-04-11 10:43 UTC, karstens commented
@GarthDB This is ready to merge.

2024-04-11 13:51 UTC, merged